export enum UserActions {
    DELETE_ACTICLE = 'DELETE_ACTICLE',
    CREATE_ARTICLE = 'CREATE_ARTICLE',
    EDIT_ARTICLE = 'EDIT_ARTICLE',
    SEND_COMMENT = 'SEND_COMMENT',
    REGISTRATION_USER = 'REGISTRATION_USER'
}