name: testing, building
on: 
  push:
    branches: [ master ]
  pull_request: 
    btanches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - users: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }} 
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: build development project
        run: npm run build:dev
      - name: unit testing
        run: npm run test:unit